### PR TITLE
chore(docker): add Dockerfile for containerizing the application

### PR DESCRIPTION
**Pull request by munna-yadav**
### PR Fixes:
Resolves issue #3 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by geekyharsh05** [comment]
@munna-yadav Looks fine for now. But can you add Docker Compose too.

**Comment by munna-yadav** [comment]
@geekyharsh05 since it is a single stage app, is the docker compose really needed?

**Comment by geekyharsh05** [comment]
@munna-yadav In order to avoid running multiple commands, we can do `docker compose up`. directly it will be easy.

**Comment by munna-yadav** [comment]
@geekyharsh05 got it. Adding

**Pull request merged**
